name: Node.js CI

on:
    push:
        branches: [dev]

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['12', '14', '16']
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - name: Installing dependencies
              run: npm install --legacy-peer-deps
            - name: Running Eslint
              run: npm run jslint
            - name: Running CSS lint
              run: npm run stylelint
            - name: Running Prettier
              run: npm run format
